<?php
	if(!empty($user))
		{
			?>
				<span class="username">Ласкаво просимо, <a href="/user"><?=$user;?></a></span>
			<?php
		}
	else
		{
			?>
				<span class="username"><a href="/user">Увійти в систему</a></span>
			<?php
		}
?>
<!-- Page Title -->
        <div class="page-title-container">
            <div class="container">
                <div class="row">
                    
                </div>
            </div>
        </div>

        <!-- About Us Text -->
        <div class="about-us-container">
        	<div class="container">
	            <div class="row">
	                <div class="col-sm-12 about-us-text wow fadeInLeft">
	                    <div id="cms_content">
											<h3>Шаблон договору оренди квартири або приміщення:</h3>

							<p><a target="_blank" href="https://docs.google.com/document/d/1Yfy-k2NltLKysVGaUdmyxx51eRfkwEBTcRwvWugW8mM/pub">Договір оренди нерухомості - відкрити зразок у новому вікні</a></p>

							<p><iframe width="800" height="600" frameborder="1" align="left" src="https://docs.google.com/document/d/1Yfy-k2NltLKysVGaUdmyxx51eRfkwEBTcRwvWugW8mM/pub?embedded=true" scrolling="yes" name="Договір оренди нерухомості" longdesc="Договір оренди нерухомості - зразок / шаблон"></iframe></p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>
							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>

							<p>&nbsp;</p>


							<h3>Чи дійсний договір оренди, якщо він не завірений у нотаріуса?</h3>

							<p>Так, дійсний. Переважна більшість договорів оренди не реєструються у нотаріуса.&nbsp; При необхідності, договір, навіть не завірений нотаріусом, може бути розглянутий в суді. Для того щоб договір мав юридичну силу, необхідна наявність на ньому точних паспортних даних господаря і квартиранта, місця їх реєстрації, а також їх особистих підписів. Також дуже важливо договір заповнювати правильно.</p>

							<h3>Як правильно заповнити договір оренди?&nbsp;</h3>

							<h4>Рейтинг найчастіших помилок при заповненні договору оренди приміщення:</h4>

							<ol>
								<li><strong>Адреса та опис квартири, </strong><span>Договір оренди обов'язково повинен включати такі пункти: повний! опис квартири з вказівкою адреси.</span></li>
								<li><strong>Хто власник? Право власності</strong>. Договір оренди обов'язково повинен включати такі пункти: відомості про власників і реквізити документів, що підтверджують право власності на квартиру.&nbsp;</li>
								<li><strong>Реквізити сторін.</strong> Часто при самостійному укладення договору пропускається внесення реквізитів сторін повністю.</li>
								<li><strong>Помилки в описі оплати.</strong> Договір повинен містити грамотно описану: форму оплати за оренду (орендну ставку та комунальні платежі, показники лічильників) та строки оплати (коли та як проводитиметься оплата).</li>
								<li><strong>Оплата в іноземній валюті.</strong>&nbsp;Неприпустимо вказувати суми розрахунку в доларах, євро та інших іноземних валютах.</li>
								<li><strong>Акт прийому-передачі нерухомого майна.</strong> Додається до договору.&nbsp;</li>
							</ol>

							<h3>Акт прийому-передачі приміщення - зразок (додається до договору оренди)</h3>

							<p><a target="_blank" href="https://docs.google.com/document/d/1qYInezbk1PeJ-1BbBopIRQ6po1Ztqmw_YxZTsloUYd0/pub">Акт прийому-передачі - відкрити зразок у новому вікні</a></p>

							<p><iframe width="800" height="300" frameborder="1" src="https://docs.google.com/document/d/1qYInezbk1PeJ-1BbBopIRQ6po1Ztqmw_YxZTsloUYd0/pub?embedded=true" scrolling="yes"></iframe></p>

							<p><span>Юристи не рекомендують складати договір оренди нерухомості самостійно. Так Ви наражаєтеся на небезпеку неправильно укласти угоду або опустити важливі моменти та не узгодити їх з орендарем. Щоб уникнути цього рекомендуємо скористатися послугами ріелторів або юристів.</span></p>
							</div>
	                </div>
	            </div>
	        </div>
        </div>