<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Agency')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Droid+Sans">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lobster">
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/ico/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('js/bootstrap/css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/magnific-popup.css'))
                        ->prependStylesheet($this->basePath('css/flexslider.css'))
                        ->prependStylesheet($this->basePath('css/form-elements.css'))
                        ->prependStylesheet($this->basePath('css/media-queries.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/animate.css')) ?>                                    
        <!-- Scripts -->
        <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <?php echo $this->headScript()
            
            ->prependFile($this->basePath('js/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/bootstrap-hover-dropdown.min.js'))
            ->prependFile($this->basePath('js/jquery.backstretch.min.js'))
            ->prependFile($this->basePath('js/wow.min.js'))
            ->prependFile($this->basePath('js/retina-1.1.0.min.js'))
            ->prependFile($this->basePath('js/jquery.magnific-popup.min.js'))
            ->prependFile($this->basePath('js/jflickrfeed.min.js'))
            ->prependFile($this->basePath('js/masonry.pkgd.min.js'))
            ->prependFile($this->basePath('js/jquery.ui.map.min.js'))
            ->prependFile($this->basePath('js/scripts.js'))
            ->prependFile($this->basePath('js/flexslider/jquery.flexslider-min.js'))
        ; ?>
        
    </head>
            <!-- Top menu -->
        <nav class="navbar" role="navigation">
	<div class="container">
                        <div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
                                </button>
		<a class="navbar-brand" href="/">Agency - a super cool design agency...</a>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="top-navbar-1">
                        <ul class="nav navbar-nav navbar-right">
                                <li class="active">
                                        <a href="/" >
                                                <i class="fa fa-home"></i><br>Home
                                        </a>               
                                </li>
                                <li>
                                        <a href="/adverts"><i class="fa fa-camera"></i><br>Catalog</a>
                                </li>
                                <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000"><i class="fa fa-comments"></i><br>Blog<span class="caret"></span></a>
                                </li>
                                <li>
                                        <a href="services.html"><i class="fa fa-tasks"></i><br>Services</a>
                                </li>
                                <li>
                                        <a href="about.html"><i class="fa fa-user"></i><br>About</a>
                                </li>
                                <li>
                                        <a href="contact.html"><i class="fa fa-envelope"></i><br>Contact</a>
                                </li>
                        </ul>
                        </div>
                </div>
        </nav>
        
        <?php echo $this->content; ?>

        <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-3 footer-box wow fadeInUp">
                        <h4>About Us</h4>
                        <div class="footer-box-text">
	                        <p>
	                        	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. 
	                        	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et.
	                        </p>
	                        <p><a href="about.html">Read more...</a></p>
                        </div>
                    </div>
                    <div class="col-sm-3 footer-box wow fadeInDown">
                        <h4>Email Updates</h4>
                        <div class="footer-box-text footer-box-text-subscribe">
                        	<p>Enter your email and you'll be one of the first to get new updates:</p>
                        	<form role="form" action="/subscribe.php" method="post">
		                    	<div class="form-group">
		                    		<label class="sr-only" for="subscribe-email">Email address</label>
		                        	<input type="text" name="email" placeholder="Email..." class="subscribe-email" id="subscribe-email">
		                        </div>
		                        <button type="submit" class="btn">Subscribe</button>
		                    </form>
		                    <p class="success-message"></p>
		                    <p class="error-message"></p>
                        </div>
                    </div>
                    <div class="col-sm-3 footer-box wow fadeInUp">
                        <h4>Flickr Photos</h4>
                        <div class="footer-box-text flickr-feed"></div>
                    </div>
                    <div class="col-sm-3 footer-box wow fadeInDown">
                        <h4>Contact Us</h4>
                        <div class="footer-box-text footer-box-text-contact">
	                        <p><i class="fa fa-map-marker"></i> Address: Via Principe Amedeo 9, 10100, Torino, TO, Italy</p>
	                        <p><i class="fa fa-phone"></i> Phone: 0039 333 12 68 347</p>
	                        <p><i class="fa fa-user"></i> Skype: Andia_Agency</p>
	                        <p><i class="fa fa-envelope"></i> Email: <a href="">contact@andia.co.uk</a></p>
                        </div>
                    </div>
                </div>
                <div class="row">
                	<div class="col-sm-12 wow fadeIn">
                		<div class="footer-border"></div>
                	</div>
                </div>
                <div class="row">
                    <div class="col-sm-7 footer-copyright wow fadeIn">
                        <p>Copyright 2012 Andia - All rights reserved. Template by <a href="http://azmind.com">Azmind</a>.</p>
                    </div>
                    <div class="col-sm-5 footer-social wow fadeIn">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                    </div>
                </div>
            </div>
        </footer>
    </body>

</html>