<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Agency')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Droid+Sans">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lobster">
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/ico/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('js/bootstrap/css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/magnific-popup.css'))
                        ->prependStylesheet($this->basePath('css/flexslider.css'))
                        ->prependStylesheet($this->basePath('css/form-elements.css'))
                        ->prependStylesheet($this->basePath('css/media-queries.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/animate.css')) ?>                                    
        <!-- Scripts -->
        
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
        <?php echo $this->headScript()
            
            ->prependFile($this->basePath('js/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/bootstrap-hover-dropdown.min.js'))
            ->prependFile($this->basePath('js/jquery.backstretch.min.js'))
            ->prependFile($this->basePath('js/wow.min.js'))
            ->prependFile($this->basePath('js/retina-1.1.0.min.js'))
            ->prependFile($this->basePath('js/jquery.magnific-popup.min.js'))
            ->prependFile($this->basePath('js/jflickrfeed.min.js'))
            ->prependFile($this->basePath('js/masonry.pkgd.min.js'))
            ->prependFile($this->basePath('js/jquery.ui.map.min.js'))
            ->prependFile($this->basePath('js/scripts.js'))
            ->prependFile($this->basePath('js/flexslider/jquery.flexslider-min.js'))
        ; ?>
        
    </head>
            <!-- Top menu -->
        <nav class="navbar" role="navigation">
	<div class="container">
                        <div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
                                </button>
									<a class="navbar-brand" href="/"><span class="great_font">Agency</span></a>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
								<div class="collapse navbar-collapse">
									<form method="POST" action="/adverts">
										<div id="search">
											<input type="text" id="search_key" name="search_key"/>
											<input type="submit" name="search_sub" value="Пошук" />
										</div>
									</form>
							  </div>
                        <div class="collapse navbar-collapse" id="top-navbar-1">
								<?php // <-- Update this !!
									echo $this->navigation('navigation')
												 ->menu()
												 ->setMinDepth(0)
												 ->setMaxDepth(0)
												 ->setUlClass('nav navbar-nav navbar-right');
									?>	
                        </div>
                </div>
        </nav>
        <?php echo $this->content; ?>

        <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-3 footer-box wow fadeInUp new_width">
                        <h4>Хто ми такі?</h4>
                        <div class="footer-box-text">
	                        <p>
	                        	Компанія, послугами якої користуються клієнти з 2015 року, яка змінює ринок нерухомості для своїх клієнтів у кращу сторону, компанія, яку визнають як єдиного лідера ринку нерухомості Ужгорода.
	                        </p>
	                        
                        </div>
                    </div>
                    <div class="col-sm-3 footer-box wow fadeInDown new_width">
                        <h4>Дивіться також</h4>
                        <div class="footer-box-text ">
									<a href="http://sfs.gov.ua/nove-pro-podatki--novini-/109647.html" >Порядок оподаткування доходів від продажу нерухомості</a><br/>
									<a href="http://notarius.ks.ua/index.php?id=11&sid=6c8b0e1276ed4c7c1ba7e14f7ed1f2a2">Договір купівлі-продажу квартири</a><br/>
									<a href="http://texty.org.ua/pg/article/editorial/read/43613/Jak_teper_kupuvatyprodavaty_vlasnist_Gid_po_novyh">Гід по нових правилах реєстрації нерухомості (ІНФОГРАФІКА)</a><br/>
									<a href="http://san.in.ua/korisn%D1%96-poradi-pri-kup%D1%96vl%D1%96-nerukhomost%D1%96">Корисні поради при купівлі нерухомості</a><br/>
								</div>
                    </div>
                    <div class="col-sm-3 footer-box wow fadeInUp new_width">
                        <h4>Контакти</h4>
                        <div class="footer-box-text footer-box-text-contact">
	                        <p><i class="fa fa-map-marker"></i> Адреса: Закарпатська область, м. Ужгород</p>
	                        <p><i class="fa fa-phone"></i> Тел.: (093) 531-62-77</p>
	                        <p><i class="fa fa-user"></i> Skype: Agency</p>
	                        <p><i class="fa fa-envelope"></i> Email: <a href="">contact@agency.com.ua</a></p>
                        </div>
                    </div>
                </div>
                <div class="row">
                	<div class="col-sm-12 wow fadeIn">
                		<div class="footer-border"></div>
                	</div>
                </div>
                <div class="row">
                    <div class="col-sm-7 footer-copyright wow fadeIn">
                        <p>Copyright 2012 Andia - All rights reserved. Template by <a href="http://azmind.com">Azmind</a>.</p>
                    </div>
                    <div class="col-sm-5 footer-social wow fadeIn">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                    </div>
                </div>
            </div>
        </footer>
    </body>

</html>