<?php
	if(!empty($user))
		{
			?>
				<span class="username">Ласкаво просимо, <a href="/user"><?=$user;?></a></span>
			<?php
		}
	else
		{
			?>
				<span class="username"><a href="/user">Увійти в систему</a></span>
			<?php
		}
?>
<!-- Page Title -->
        <div class="page-title-container">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 wow fadeIn">
                        <!--<i class="fa fa-camera"></i>-->
                        
								<?php
									if(empty($message))
										{
											echo '<h1>Каталог</h1><p></p>';
										}
									else
										{
											echo '<h1>'.$message.'</h1>';
										}
								?>
                    </div>
                </div>
            </div>
        </div>

        <!-- Portfolio -->
        <div class="portfolio-container">
	        <div class="container">
	            <div class="row">
	            	<div class="col-sm-12 portfolio-filters wow fadeInLeft">
	            		<a href="#" class="filter-all active">Всі</a> / 
							<?php
							foreach($categories as $category)
								{
									?>
									<a href="#" class="filter-<?=$category->id;?>"><?=$category->name;?></a> / 
									<?php
								}
							?>
	            	</div>
	            </div>
	            <div class="row">
	            	<div class="col-sm-12 portfolio-masonry">
                     <?php foreach ($adverts as $advert) :?>
							<?php 
								$images = explode(",", $advert->pictures);
							?>
		                <div class="portfolio-box <?=$advert->category_id;?>">
		                	<div class="portfolio-box-container">
			                	<img class="advert_image" src="<?= $images[0]; ?>" alt="" data-at2x="<?= $images[0]; ?>">
                                                <a href="/adverts/advert/<?= $this->escapeHtml($advert->id);?>">
                                                    <div class="portfolio-box-text advert_text_box">
			                		<h3><?= $this->escapeHtml($advert->title);?></h3>
			                		<p class="advert_description"><?= $this->escapeHtml($advert->address);?></p>
                                                    </div>
                                                </a>
			                </div>
		                </div>
                     <?php endforeach; ?>
	                </div>
	            </div>
	        </div>
        </div>