<?php
	if(!empty($user))
		{
			?>
				<span class="username">Ласкаво просимо, <a href="/user"><?=$user;?></a></span>
			<?php
		}
	else
		{
			?>
				<span class="username"><a href="/user">Увійти в систему</a></span>
			<?php
		}
?>
<!-- Page Title -->
        <div class="page-title-container">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 wow fadeIn">
                        <!--<i class="fa fa-envelope"></i>-->
                        <h1><?= $advert->title; ?></h1>
								<p><?= $advert->date; ?></p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Contact Us -->
        <div class="contact-us-container">
        	<div class="container">
	            <div class="row">
	                <div class="col-sm-7 contact-form wow fadeInLeft">
	                    <p>
	                    	<?= $advert->description; ?>
	                    </p>
	                </div>
						
	                <div class="col-sm-5 contact-address wow fadeInUp">
	                    <h3>Location</h3>
	                    <div id="map-canvas" style="height:300px; width:400px;"></div>
	                    <h3>Address</h3>
	                    <p><?= $advert->address; ?></p>
	                    <p>Phone: <?= $advert->phone; ?></p>
	                </div>
						
						<div class="flexslider advert_images">
                            <ul class="slides">
										<?php foreach ($images as $image) :?>
                                 <li data-thumb="<?= $image;?>">
                                    <img src="<?= $image;?>">
                                 </li>
										<?php endforeach; ?>
                            </ul>
                        </div>
	            </div>
	        </div>
        </div>
<script>
$( document ).ready(function() {
	//initialize();
});
	function initialize() {
		var myLatlng = new google.maps.LatLng(48.6179734,22.2783973);
		var coord = new google.maps.LatLng(<?=$advert->coordinates;?>);
		var mapOptions = {
		  zoom: 12,
		  center: myLatlng
		}
		var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

		var marker = new google.maps.Marker({
			 position: coord,
			 map: map,
			 title: 'Hello World!'
		});
	}

google.maps.event.addDomListener(window, 'load', initialize);


</script>
			  