<?php
	if(!empty($user))
		{
			?>
				<span class="username">Ласкаво просимо, <a href="/user"><?=$user;?></a></span>
			<?php
		}
	else
		{
			?>
				<span class="username"><a href="/user">Увійти в систему</a></span>
			<?php
		}
?>
<!-- Slider -->
        <div class="slider-container">
            <div class="container">
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1 slider">
                        <div class="flexslider">
                            <ul class="slides">
                                <li data-thumb="img/slider/1.jpg">
                                    <img src="img/slider/1.jpg">
                                    <div class="flex-caption">
                                    	Агентство нерухомості "Agency" працює на ринку України з 2003 року.
                                    </div>
                                </li>
                                <li data-thumb="img/slider/2.jpg">
                                    <img src="img/slider/2.jpg">
                                    <div class="flex-caption">
                                    	Ціль нашої роботи – практична та ефективна допомога у вирішенні усіх питань, пов'язаних з нерухомістю.
                                    </div>
                                </li>
                                <li data-thumb="img/slider/3.jpg">
                                    <img src="img/slider/3.jpg">
                                    <div class="flex-caption">
                                    	Як агентсво нерухомості ми надаємо повний спектр ріелторських послуг
                                    </div>
                                </li>
                                <li data-thumb="img/slider/4.jpg">
                                    <img src="img/slider/4.jpg">
                                    <div class="flex-caption">
                                    	Багаторічний досвід провадження операцій з нерухомістю (купівля, продаж, оренда) дозволmainяє нам максимально зекономити Ваш час та зусилля, а також запропонувати Вам найкращу нерухомість. 
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Presentation -->
        <div class="presentation-container">
        	<div class="container">
        		<div class="row">
	        		<div class="col-sm-12 wow fadeInLeftBig">
	            		<h1>Вітаємо Вас на сайті агентства нерухомості <span class="violet">Agency</span></h1>
	            		<p>Комерційна та житлова нерухомість в Ужгороді, оренда квартир .</p>
	            	</div>
            	</div>
        	</div>
        </div>

        <!-- Services -->
        <div class="services-container">
	        <div class="container">
	            <div class="row">
	            	<div class="col-sm-3">
		                <div class="service wow fadeInUp">
		                    <div class="service-icon"><i class="fa fa-eye"></i></div>
		                    <h3>Як підготувати квартиру до оренди?</h3>
		                    <p>Як здати квартиру дорого?  Поради власнику як здати квартиру вигідно та швидко. Чи потрібні меблі, інтернет, побутова техніка, пральна машинка. Який ремонт. </p>
								  <a class="big-link-1" href="/state1">Детальніше</a>
		                </div>
					</div>
					<div class="col-sm-3">
		                <div class="service wow fadeInDown">
		                    <div class="service-icon"><i class="fa fa-table"></i></div>
		                    <h3>Причини продажу власниками нерухомості у 2015 році</h3>
		                    <p>8 причин по яких продають квартири. Великий сегмент потенційних покупців за останні місяці завмер в очікуваннях падіння ціни</p>
		                    <a class="big-link-1" href="/state2">Детальніше</a>
		                </div>
	                </div>
	                <div class="col-sm-3">
		                <div class="service wow fadeInUp">
		                    <div class="service-icon"><i class="fa fa-magic"></i></div>
		                    <h3>Топ-5 самих простих способів обдурити Вас на ринку нерухомості</h3>
		                    <p>Топ- 5 найбільш банальних способів шахрайства з нерухомістю, з якими можна зустрітися навіть у сьогоднішній час.</p>
		                    <a class="big-link-1" href="/state3">Детальніше</a>
		                </div>
	                </div>
	                <div class="col-sm-3">
		                <div class="service wow fadeInDown">
		                    <div class="service-icon"><i class="fa fa-print"></i></div>
		                    <h3>Чи дійсний договір оренди, якщо він не завірений у нотаріуса?</h3>
		                    <p>Переважна більшість договорів оренди не реєструються у нотаріуса. При необхідності, договір, навіть не завірений нотаріусом, може бути розглянутий в суді.</p>
		                    <a class="big-link-1" href="/state4">Детальніше</a>
		                </div>
	                </div>
	            </div>
	        </div>
        </div>

        <!-- Latest work -->
        <div class="work-container">
	        <div class="container">
	        	<div class="row">
		            <div class="col-sm-12 work-title wow fadeIn">
		                <h2>Остані добавлені</h2>
		            </div>
	            </div>
	            <div class="row">
	            	
							<?php $i = 1; 
		               for($j = $count-1; $j > ($count - 6); $j--)
								{
								$images = explode(",", $adverts[$j]['pictures']);
								switch($i)
									{
										case 1:
											$class = "fadeInDown";
											break;
										case 2:
											$class = "fadeInUp";
											break;
										case 2:
											$class = "fadeInDown";
											break;
										case 2:
											$class = "fadeInUp";
											break;
									}
								if($i < 5)
									{
								?>
									<div class="col-sm-3">
										<div class="work wow <?=$class;?>">
											<a href="/adverts/advert/<?= $this->escapeHtml($adverts[$j]['id']);?>">
											 <img src="<?= $images[0]; ?>"  data-at2x="<?= $images[0]; ?>">
											 <h3><?= $this->escapeHtml($adverts[$j]['title']);?></h3>
											 <p><?= $this->escapeHtml($adverts[$j]['description']);?></p>
											</a>
										</div>
									</div>	
							<?php } 
								$i++;
							?>
								<?php } ?>
	                
	                
	            </div>
	        </div>
        </div>

        <!-- Testimonials -->
        <div class="testimonials-container">
	        <div class="container">
	        	<div class="row">
		            <div class="col-sm-12 testimonials-title wow fadeIn">
		                <h2>Testimonials</h2>
		            </div>
	            </div>
	            <div class="row">
	                <div class="col-sm-10 col-sm-offset-1 testimonial-list">
	                	<div role="tabpanel">
	                		<!-- Tab panes -->
	                		<div class="tab-content">
	                			<div role="tabpanel" class="tab-pane fade in active" id="tab1">
	                				<div class="testimonial-image">
	                					<img src="img/testimonials/1.jpg" alt="" data-at2x="img/testimonials/1.jpg">
	                				</div>
	                				<div class="testimonial-text">
		                                <p>
		                                	"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. 
		                                	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. 
		                                	Lorem ipsum dolor sit amet, consectetur..."<br>
		                                	<a href="#">Lorem Ipsum, dolor.co.uk</a>
		                                </p>
	                                </div>
	                			</div>
	                			<div role="tabpanel" class="tab-pane fade" id="tab2">
	                				<div class="testimonial-image">
	                					<img src="img/testimonials/2.jpg" alt="" data-at2x="img/testimonials/2.jpg">
	                				</div>
	                				<div class="testimonial-text">
		                                <p>
		                                	"Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip 
		                                	ex ea commodo consequat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit 
		                                	lobortis nisl ut aliquip ex ea commodo consequat..."<br>
		                                	<a href="#">Minim Veniam, nostrud.com</a>
		                                </p>
	                                </div>
	                			</div>
	                			<div role="tabpanel" class="tab-pane fade" id="tab3">
	                				<div class="testimonial-image">
	                					<img src="img/testimonials/3.jpg" alt="" data-at2x="img/testimonials/3.jpg">
	                				</div>
	                				<div class="testimonial-text">
		                                <p>
		                                	"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. 
		                                	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. 
		                                	Lorem ipsum dolor sit amet, consectetur..."<br>
		                                	<a href="#">Lorem Ipsum, dolor.co.uk</a>
		                                </p>
	                                </div>
	                			</div>
	                			<div role="tabpanel" class="tab-pane fade" id="tab4">
	                				<div class="testimonial-image">
	                					<img src="img/testimonials/1.jpg" alt="" data-at2x="img/testimonials/1.jpg">
	                				</div>
	                				<div class="testimonial-text">
		                                <p>
		                                	"Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip 
		                                	ex ea commodo consequat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit 
		                                	lobortis nisl ut aliquip ex ea commodo consequat..."<br>
		                                	<a href="#">Minim Veniam, nostrud.com</a>
		                                </p>
	                                </div>
	                			</div>
	                		</div>
	                		<!-- Nav tabs -->
	                		<ul class="nav nav-tabs" role="tablist">
	                			<li role="presentation" class="active">
	                				<a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab"></a>
	                			</li>
	                			<li role="presentation">
	                				<a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab"></a>
	                			</li>
	                			<li role="presentation">
	                				<a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab"></a>
	                			</li>
	                			<li role="presentation">
	                				<a href="#tab4" aria-controls="tab4" role="tab" data-toggle="tab"></a>
	                			</li>
	                		</ul>
	                	</div>
	                </div>
	            </div>
	        </div>
        </div>
